---
- name: Start custom IBM MQ Queue Manager
  hosts: mq_servers
  become: yes
  become_user: mqm
  vars:
    qmgr_name: "{{ qmgr_name }}"
  tasks:

    - name: Verify the status of the webconsole
      shell: dspmqweb status
      register: web_status

    - debug:
        msg: "Status of Web: {{ web_status.stdout }}"
