---
- name: Start custom IBM MQ Queue Manager
  hosts: mq_servers
  become: yes
  become_user: mqm

  tasks:
 
    - name: Start the webconsole
      shell: strmqweb
      register: web_status
      ignore_errors: yes

    - debug:
        msg: "Start of the  Webconsole: {{ web_status.stdout }}"

    - name: Verify the status of the webconsole
      shell: dspmqweb status
      register: web_status

    - debug:
        msg: "Status of Web: {{ web_status.stdout }}"